package com.example.comic_Market

import java.net.URL

data class Circle(
    val check: Boolean,
    val user: String?,
    val week :Week?,
    val hall: Hall?,
    val space: String?,
    val name: String?,
    val writer: String?,
    val twitter: URL?,
    val memo: String?,
    val price: Int?,
    val assign: String?,
)
enum class Week(val kanji: String) {
    Sun("日"),
    Mon("月"),
    Tue("火"),
    Wed("水"),
    Thu("木"),
    Fri("金"),
    Sat("土");
}
enum class Hall(val kanji: String) {
    East("東"),
    West("西"),
    South("南");
}
fun generateDummyCircles(): List<Circle> =
    listOf(
        Circle(true, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(false, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(true, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
        Circle(true, "ex_user", Week.Sun, Hall.East, "a14a", "ex_circle", "ex_writer", URL("https://example.com/circle"), "新刊、おそらく500円",500,"ex_user"),
    )

fun parseWeek(input: String): Week? {
    return Week.values().find { it.kanji == input }
}
